spring:
  security:
    user:
      name: "ADMX"
      password: "ADMX"
  boot:
    admin:
      client:
        username: "ADMX"       #These two are needed so that the client
        password: "ADMX"   #can register at the protected server api
        instance:
          metadata:
            user.name: "ADMX"         #These two are needed so that the server
            user.password: "ADMX" #can access the protected client endpoints
          prefer-ip: true
          service-host-type: host_name
        url: localhost:8080

info.tags.security: secured
